max-name-length: 30         # Maksymalna długość nazwy (0 = brak limitu)
max-lore-lines: 5           # Maksymalna liczba linii lore (0 = brak limitu)
max-lore-line-length: 50    # Maksymalna długość pojedynczej linii lore (0 = brak limitu)
