name: PexRename
version: 1.0
main: com.micx.pexrename.Main
commands:
  rename:
    description: Zmienia nazwę przedmiotu.
    permission: pex.rename
  zmiennazwe:
    description: Zmienia nazwę przedmiotu.
    permission: pex.rename
  setlore:
    description: Ustawia lore przedmiotu.
    permission: pex.setlore
  ustawlore:
    description: Ustawia lore przedmiotu.
    permission: pex.setlore
