name: Pex.Rename
version: 1.0
main: com.micx.pexrename.Main
commands:
  rename:
    description: Zmienia nazwę trzymanego przedmiotu.
    usage: /rename <new name>
    permission: pex.rename
    permission-message: "Nie masz pozwolenia do używania tej komendy."
  zmiennazwe:
    description: Zmienia nazwę trzymanego przedmiotu.
    usage: /zmiennazwe <nowa nazwa>
    permission: pex.rename
    permission-message: " Nie masz pozwolenia do używania tej komendy."
permissions:
  pex.rename:
    description: Pozwala na zmianę nazwy przedmiotu.
    default: op
